(** The two facts {!Handsome.Utf8_width} needs about a code point, as tables
    generated from the Unicode Character Database.

    [unicode_tables.ml] is generated by [tools/gen_unicode_tables.py]; a change
    to it comes from regenerating, and [dune build @unicode] checks it against
    the release it names. This interface is written by hand, staying fixed as
    the tables move. *)

(** The Unicode release the tables were generated from. *)
val unicode_version : string

(** Code points two columns wide: East_Asian_Width Wide or Fullwidth, plus the
    ranges whose unassigned code points default to Wide. *)
val wide : int array

(** Code points that occupy no columns: General_Category Mn, Me or Cf. *)
val zero : int array

(** [mem t u] is whether [u] falls in one of [t]'s ranges.

    [t] is inclusive ranges flattened and sorted — [t.(2*i)] and [t.(2*i+1)] are
    the bounds of range [i], ascending and disjoint — so this is a binary
    search. *)
val mem : int array -> int -> bool
